name: Pipeline CI/CD
run-name: Pipeline CI/CD executada por ${{github.actor}} em ${{github.run_number}}

on: 
    workflow_dispatch:
    push:
      branches:
        - main

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Obtendo o código do projeto
              uses: actions/checkout@v7.0.1            

            - name : Setup dotnet
              uses: actions/setup-dotnet@v6.0.0
              with:
                dotnet-version: "8.0.300"

            - name: Execução do comando build
              working-directory: ./src
              run: dotnet build Review-Filmes.sln
    testes:
      needs: [build]
      uses: ./.github/workflows/testes.yml
      secrets: inherit
    
    release:
      name: Criação de Release
      runs-on: ubuntu-latest
      needs: [testes]
      permissions:
        contents: read
        actions: read
        security-events: write
      steps:
        - name: Obtendo código do projeto
          uses: actions/checkout@v7.0.1

        - name: Analise do Dockerfile
          uses: hadolint/hadolint-action@v3.1.0
          with:
            dockerfile: ./src/Review-Filmes.Web/Dockerfile
 
        - name: Efetuando login no Docker Hub
          uses: docker/login-action@v4.5.1
          with:
            username: ${{secrets.DOCKERHUB_USER}}
            password: ${{secrets.DOCKERHUB_PWD}}

        - name: Build e Push da Imagem Docker
          uses: docker/build-push-action@v7.3.0
          with:
            push : true
            context : ./src
            file: ./src/Review-Filmes.Web/Dockerfile
            tags: |
                yuriromaodocker/projeto-devops-pro:latest
                ${{secrets.DOCKERHUB_USER}}/projeto-devops-pro:v${{ github.run_number }}

        - name: Executar o Trivy
          uses: aquasecurity/trivy-action@v0.9.0
          with:
            image-ref: yuriromaodocker/projeto-devops-pro:v${{ github.run_number }}
            format: sarif
            output: trivy-docker-result.sarif
            severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
        
        - name: Upload do resultado do Trivy
          uses: github/codeql-action/upload-sarif@v4
          with:
            category: "trivy-docker"
            sarif_file: trivy-docker-result.sarif

    deploy-homolog:
      needs: [release]
      name: Deploy em Kind (self-hosted)
      uses: ./.github/workflows/deploy.yml
      with:
        image: yuriromaodocker/projeto-devops-pro:v${{ github.run_number }}
      secrets: inherit