name: Execução de Testes
on: 
    workflow_call:
        secrets:
            SONAR_TOKEN:
                required: true

jobs:
    unit-test:
        name: Execução de Testes Unidade
        runs-on: ubuntu-latest
        steps:
            - name: Obtendo o código do projeto
              uses: actions/checkout@v7.0.1            

            - name : Setup dotnet
              uses: actions/setup-dotnet@v6.0.0
              with:
                dotnet-version: "8.0.300"

            - name: Execução do teste de Unidade
              working-directory: ./src
              run: dotnet test ./Review-Filmes.Test.Unit/Review-Filmes.Test.Unit.csproj
    
    integration-test:
        name: Execução de Testes Integração
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:15.3
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: 123456
                    POSTGRES_DB: review-filmes-db
                ports:
                    - 5432:5432

        steps:
            - name: Obtendo o código do projeto
              uses: actions/checkout@v7.0.1            

            - name : Setup dotnet
              uses: actions/setup-dotnet@v6.0.0
              with:
                dotnet-version: "8.0.300"
            
            - name: Execução do teste de Integração
              working-directory: ./src
              run: dotnet test ./Review-Filmes.Test.Integration/Review-Filmes.Test.Integration.csproj
              env:
                ConnectionStrings__DefaultConnection: "Server=localhost;Port=5432;Database=review-filmes-db;User Id=postgres;Password=123456;"
    
    sonarqube:
        name: Análise de Código com SonarQube
        runs-on: ubuntu-latest

        steps:
            - name: Obtendo o código do projeto
              uses: actions/checkout@v7.0.1
              with:
                fetch-depth: 0

            - name: Configurando .NET
              uses: actions/setup-dotnet@v6.0.0
              with:
                dotnet-version: "8.0.300"

            - name: Instalando SonarScanner
              run: dotnet tool install --global dotnet-sonarscanner

            - name: Iniciando análise SonarQube
              working-directory: ./src
              run: |
                dotnet sonarscanner begin \
                /k:"Projeto-Testee_migracao3" \
                /o:"projeto-testee1" \
                /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

            - name: Compilando aplicação
              working-directory: ./src
              run: dotnet build Review-Filmes.sln

            - name: Finalizando análise SonarQube
              working-directory: ./src
              run: |
                    dotnet sonarscanner end \
                    /d:sonar.token="${{ secrets.SONAR_TOKEN }}" 
